SYMBOLS = {
    "NIFTY": "NIFTY 50",
    "RELIANCE": "RELIANCE",
    "HDFCBANK": "HDFCBANK"
}

TIMEFRAME = "minute"
LOOKBACK_MONTHS = 6

VOLUME_MULTIPLIER = 1.2
STRUCTURE_LOOKBACK = 3
MICRO_RANGE = 5

STOP_LOSS_POINTS = 20

TRADE_START_TIME = "09:20"
TRADE_END_TIME = "14:00"
FORCE_EXIT_TIME = "14:45"
